name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./app
        run: npm install

      - name: Run tests
        working-directory: ./app
        run: npm test

      - name: Build project
        working-directory: ./app
        run: npm run build
